import torch
from torch.nn.functional import mse_loss
from operators.lddmm.deform import FlowDeformationOperator
from operators.lddmm.helmholtz import HelmholtzOperator
from dataclasses import dataclass
from typing import overload

@dataclass
class LDDMMLoss:
    data_loss: torch.Tensor
    regularization_loss: torch.Tensor
    total_loss: torch.Tensor


class LDDMMloss(torch.nn.Module):
    r"""This class implements the LDDMM loss function: 
    L(v) = ||I_1 - I_0 \circ \phi_v||^2 + \lambda ||v||^2, where I_0 is the template image, I_1 is the target image, v is the velocity field, and \phi_v is the deformation field generated by integrating v. 
    The first term measures the similarity between the deformed template and the target, while the second term regularizes the velocity field to ensure smooth deformations."""
    
    def __init__(self, 
                flow_deform_op: FlowDeformationOperator,
                 helmholtz_op: HelmholtzOperator,
                 lambda_reg=0.1,
                 device=torch.device("cpu")):
        super(LDDMMloss, self).__init__()
        self.lambda_reg = lambda_reg
        self.flow_deform_op = flow_deform_op  # Use the provided FlowDeformationOperator
        self.helmholtz_op = helmholtz_op  # Use the provided Helmholtz operator
        self.device = device

        # Ensure the operators are on the same device as the loss module

        assert self.flow_deform_op.device == self.device and self.helmholtz_op.device == self.device, f"FlowDeformationOperator and HelmholtzOperator must be on the same device but got {self.flow_deform_op.device} and {self.helmholtz_op.device}"
        self.to(self.device)


    @overload
    def forward(self, x: torch.Tensor, y: torch.Tensor, v: torch.Tensor) -> tuple[LDDMMLoss, torch.Tensor]: ...

    @overload
    def forward(self, x: torch.Tensor, y: list[torch.Tensor], v: list[torch.Tensor]) -> tuple[LDDMMLoss, list[torch.Tensor]]: ...

    def forward(self, x: torch.Tensor, y: torch.Tensor | list[torch.Tensor], v: torch.Tensor | list[torch.Tensor]) -> tuple[LDDMMLoss, list[torch.Tensor] | torch.Tensor]:
        # Compute the deformation field by integrating the velocity field

        if isinstance(y, list):
            assert isinstance(v, list) and len(v) == len(y), f"If y is a list with length {len(y)}, v must also be a list of the same length but got type {type(v)} and length {len(v)}"

        if isinstance(y, list):
            out = [self.forward(x, y_i, v_i) for y_i, v_i in zip(y, v)]

            # Sum the losses and stack the deformed images
            total_data_loss = torch.stack([item[0].data_loss for item in out]).sum()
            total_regularization_loss = torch.stack([item[0].regularization_loss for item in out]).sum()
            total_loss = torch.stack([item[0].total_loss for item in out]).sum()
            x_deformed_list = [item[1] for item in out]

            return LDDMMLoss(
                data_loss=total_data_loss,
                regularization_loss=total_regularization_loss,
                total_loss=total_loss
            ), x_deformed_list


        x_deformed = self.flow_deform_op(x, v)[-1] # The flow-deformation operator returns [x_init, x_deformed] when v is static (a tensor)
        data_loss = mse_loss(x_deformed, y, reduction='mean')
        regularization_loss = torch.mean(self.helmholtz_op(v).square())
        total_loss = data_loss + self.lambda_reg * regularization_loss

        return LDDMMLoss(
            data_loss=data_loss,
            regularization_loss=regularization_loss,
            total_loss=total_loss
        ), x_deformed
